<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <?= $this->headTitle("PIZZ'ON")->setSeparator(' - ')->setAutoEscape(false); ?>

        <!-- Le styles -->
        <?=
                $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/pizza.png'))
                ->prependStylesheet($this->basePath() . '/css/lojaStyle.css')
                ->prependStylesheet($this->basePath() . '/css/jquery.fancybox.css')
                ->prependStylesheet($this->basePath() . '/css/jquery.bxslider.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.fancybox.pack.js')
                ->prependFile($this->basePath() . '/js/bxslider.min.js')
                ->prependFile($this->basePath() . '/js/config.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

    </head>
    <body>
        <span class="left">
            <i>&nbsp;</i>
            <i>&nbsp;</i>
            <i>&nbsp;</i>
            <i>&nbsp;</i>
            <?php if ($this->UserIdentity('Admin')): ?>
                <?php if ($this->UserIdentity('Admin')->getAdmin()): ?>
                    <a href="<?= $this->url('admin', array('controller' => 'admin', 'action' => 'index')); ?>" name="home" class="button admin">Administração</a>
                <?php endif; ?>
            <?php endif; ?>
        </span>
        <span class="right">
            <?php if ($this->UserIdentity('Admin')): ?>
                <i class="fa fa-user"></i> 
                <?= $this->UserIdentity('Admin')->getNome(); ?>
                <i class="fa fa-caret-down"></i>
                <i>&nbsp;</i>
                <i>&nbsp;</i>
                <i>&nbsp;</i>
                <i>&nbsp;</i>
            <?php else: ?>
                <form method="POST" action="/auth">
                    <label>E-Mail: <input type="text" name="email"></label>
                    <label>Senha: <input type="password" name="senha"></label>
                    <button class="button" style="width: 40px; height: 40px;">OK</button>
                    <i>&nbsp;</i>
                    <i>&nbsp;</i>
                    <i>&nbsp;</i>
                    <i>&nbsp;</i>
                </form>
            <?php endif; ?>
        </span>
        <div class="border2"></div>
        <div id="container">
            <header>
                <nav>
                    <ul id="nav">
                        <li><a href="<?= $this->url('loja', array('controller' => 'loja', 'action' => 'index')); ?>" name="home">Inicio</a></li>
                        <li><a href="<?= $this->url('loja', array('controller' => 'loja', 'action' => 'menu')); ?>" name="menu">Pizza</a></li>
                        <li><a href="<?= $this->url('loja', array('controller' => 'loja', 'action' => 'about')); ?>" name="about">Sanduiche</a></li>
                        <li><a href="<?= $this->url('loja', array('controller' => 'loja', 'action' => 'reviews')); ?>" name="reviews">Bebidas</a></li>
                        <li><a href="<?= $this->url('loja', array('controller' => 'loja', 'action' => 'gallery')); ?>" name="gallery">Galeria</a></li>
                        <li><a href="<?= $this->url('loja', array('controller' => 'loja', 'action' => 'contact')); ?>" name="contact">Contato</a></li>
                    </ul>
                </nav>
            </header>
            <?php echo $this->content; ?>
            <footer>
                <div class="border"></div>
                <div class="footer-widget" style="margin-left: 33%">
                    <h4>Redes Sociais!</h4>
                    <div id="social"> 
                        <a href="#" class="s3d twitter" target="_blank"> Twitter <span class="icons twitter"></span> </a>
                        <a href="#" class="s3d facebook" target="_blank"> Facebook <span class="icons facebook"></span> </a> 
                    </div>
                </div>
                <div class="border2"></div>
                <br />
                <span class="copyright">
                    <span class="left">
                        <p class="pull-right">Desenvolvido por caras legais do bem de verdade.<br>
                            &copy; 2014 - <?php echo date('Y') ?> Pizz'on, inc. Todos os direitos reservados.</p>
                    </span>
                </span>
            </footer>
        </div>
    </body>
</html>
