<div class="wrapper">
    <div class="border"></div>
    <article>
        <h3>Nos Encontre!</h3>
        <iframe width="625" height="250" src="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=pt-BR&amp;geocode=&amp;q=69316690&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=48.77566,86.572266&amp;ie=UTF8&amp;t=m&amp;layer=c&amp;cbll=2.851762,-60.64573&amp;panoid=jCreQRxSPl6gaDMUK46jNw&amp;cbp=13,118.09,,0,16.99&amp;ll=2.844054,-60.645733&amp;spn=0.026918,0.048237&amp;z=14&amp;output=svembed"></iframe>
        <br />
        <br />
        <h3>Tire suas Duvidas!</h3>
        <form action="#" method="post">
            <label for="name">Nome:</label>
            <br>
            <input type="text" name="name" id="name" value="" tabindex="1" />
            <br>
            <br>
            <label for="name">Assunto:</label>
            <br>
            <input type="text" name="name" id="subject" value="" tabindex="3" />
            <br>
            <br>
            <label for="name">Email:</label>
            <br>
            <input type="text" name="name" id="email" value="" tabindex="2" />
            <br>
            <br>
            <label for="textarea">Mensagem:</label>
            <br>
            <textarea cols="40" rows="8" name="textarea" id="textarea"></textarea>
            <br>
            <br>
            <input type="submit" value="Enviar" class="button" />
        </form>
        <br>
        <br>
        <br>
    </article>
    <aside class="sidebar">
        <h3>Quem Somos</h3>
        <ul class="blog">
            <li>Em 2014 comemoramos a oportunidade de oferecer a voce a melhor pizzaria online da cidade,
                com ingredientes cuidadosamente selecionados pela PIZZ'ON, garantindo qualidade e rapidez.  </li>
        </ul>
    </aside>
</div>