<div class="wrapper">
    <div class="border"></div>
    <article>
        <h3>Contate - Nos</h3>
        <iframe width="625" height="250" src="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=pt-BR&amp;geocode=&amp;q=69316690&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=48.77566,86.572266&amp;ie=UTF8&amp;t=m&amp;layer=c&amp;cbll=2.851762,-60.64573&amp;panoid=jCreQRxSPl6gaDMUK46jNw&amp;cbp=13,118.09,,0,16.99&amp;ll=2.844054,-60.645733&amp;spn=0.026918,0.048237&amp;z=14&amp;output=svembed"></iframe>
        <br />
        <p>pizzaria muito foda, hahaha, com muito lorem ipsum, us et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. In turpis pulvinar facilisis. Ut .</p>
        <form action="#" method="post">
            <label for="name">Nome:</label>
            <br>
            <input type="text" name="name" id="name" value="" tabindex="1" />
            <br>
            <br>
            <label for="name">Assunto:</label>
            <br>
            <input type="text" name="name" id="subject" value="" tabindex="3" />
            <br>
            <br>
            <label for="name">Email:</label>
            <br>
            <input type="text" name="name" id="email" value="" tabindex="2" />
            <br>
            <br>
            <label for="textarea">Mensagem:</label>
            <br>
            <textarea cols="40" rows="8" name="textarea" id="textarea"></textarea>
            <br>
            <br>
            <input type="submit" value="Enviar" class="button" />
        </form>
        <br>
        <br>
        <br>
    </article>
    <aside class="sidebar">
        <h3>informaçõeszinha</h3>
        <ul class="blog">
            <li><a href="#">Lorem Ipsum Dolor</a><br/>
                Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
            <li><a href="#">Praesent Et Eros</a><br/>
                Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
            <li><a href="#">Suspendisse In Neque</a><br/>
                Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
            <li><a href="#">Suspendisse In Neque</a><br/>
                Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
        </ul>
        <div class="border3"></div>
        <h3>muitas pizzas</h3>
        <img src="../img/images/home/1.jpg" width="280" alt="" />
        <p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. In turpis pulvinar facilisis. Ut felis.<br>
            <a href="" class="right" style="padding-top:7px"><strong>Continue Reading &raquo;</strong></a></p>
    </aside>
</div>