<div class="wrapper">
    <div class="border"></div>
    <article class="fullwidth gallery">
        <h3>Galeria</h3>
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/1.jpeg"><img src="../../img/images/gallery/1.jpeg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/2.jpg"><img src="../../img/images/gallery/2.jpg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/3.jpeg"><img src="../../img/images/gallery/3.jpeg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/4.jpg"><img src="../../img/images/gallery/4.jpg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/5.jpeg"><img src="../../img/images/gallery/5.jpeg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/6.jpg"><img src="../../img/images/gallery/6.jpg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/7.jpeg"><img src="../../img/images/gallery/7.jpeg" width="200" height="200" alt="" /></a> 
        <a class="fancyimage" data-fancybox-group="gallery" href="../../img/images/gallery/8.jpg"><img src="../../img/images/gallery/8.jpg" width="200" height="200" alt="" /></a> 
    </article>
    <br>
</div>