<header>
    <hgroup class="intro">
        <h1 class="title">PIZZ'ON</h1>
        <h3 class="tagline">Sistema para venda de pizzas onlines</h3>
    </hgroup>
    <div class="reservations"><br />
        <span class="reservations-title">Chame-nos:</span>
        <hr class="hr-solid" />
        <span class="phone-number">+095 3623 - 9999</span>
        <hr class="hr-dashed" />
        <div class="email-us"> <a class="button" href="#" title="Email Us">Ou E-Mail</a> </div>
    </div>
</header>
<div class="wrapper">
    <div class="clear"></div>
    <div class="slider2">
        <div class="slide"><img src="../../img/images/home/1.jpg"></div>
        <div class="slide"><img src="../../img/images/home/2.jpg"></div>
        <div class="slide"><img src="../../img/images/home/3.jpg"></div>
        <div class="slide"><img src="../../img/images/home/4.jpg"></div>
    </div>
    <div class="border"></div>
    <div class="home-widget">
        <h3>O Mais Pedido</h3>
        <img src="../../img/images/home/3.jpg" width="300" height="350" alt="" />
    </div>
    <div class="home-widget">
        <h3>O Flash</h3>
        <img src="../../img/images/home/4.jpg" width="300" height="350" alt="" />
    </div>
    <div class="home-widget">
        <h3>Congelante</h3>
        <img src="../../img/images/home/1.jpg" width="300" height="350" alt="" />
    </div>
    <div class="border2"></div>
    <br />
    <aside id="pricing-table" class="clear">
        <div class="plan">
            <h3>Pizzas</h3>
            <a class="button" href="/loja/loja/menu">Comprar Agora</a>
            <ul>
                <li><strong style="text-transform:uppercase">Pizza de Calabresa</strong> R$ 35,00</li>
                <li><strong style="text-transform:uppercase">Pizza de Frango</strong> R$ 33,00</li>
                <li><strong style="text-transform:uppercase">Pizza de Presunto</strong> R$ 22,00</li>
            </ul>
        </div>
        <div class="plan">
            <h3>Sanduiches</h3>
            <a class="button" href="/loja/loja/about">Comprar Agora</a>
            <ul>
                <li><strong style="text-transform:uppercase">X - Tudo</strong> R$ 15,00</li>
                <li><strong style="text-transform:uppercase">X - Salada</strong> R$ 9,00</li>
                <li><strong style="text-transform:uppercase">Mixto Quente</strong> R$ 5,00</li>
            </ul>
        </div>
        <div class="plan">
            <h3>Refrigerantes</h3>
            <a class="button" href="/loja/loja/reviews">Comprar Agora</a>
            <ul>
                <li><strong style="text-transform:uppercase">Coca Cola</strong> R$ 7,00</li>
                <li><strong style="text-transform:uppercase">Fanta Uva</strong> R$ 5,00</li>
                <li><strong style="text-transform:uppercase">Fanta Laranja</strong> R$ 5,00</li>
            </ul>
        </div>
    </aside>
</div>


