<header>
    <hgroup class="intro">
        <h1 class="title">PIZZ'ON</h1>
        <h3 class="tagline">Sistema para venda de pizzas onlines</h3>
    </hgroup>
    <div class="reservations"><br />
        <span class="reservations-title">Chame-nos:</span>
        <hr class="hr-solid" />
        <span class="phone-number">+095 3623 - 9999</span>
        <hr class="hr-dashed" />
        <div class="email-us"> <a class="button" href="#" title="Email Us">Ou E-Mail</a> </div>
    </div>
</header>
<div class="wrapper">
    <div class="clear"></div>
    <div class="slider2">
        <div class="slide"><img src="../../img/images/home/1.jpg"></div>
        <div class="slide"><img src="../../img/images/home/2.jpg"></div>
        <div class="slide"><img src="../../img/images/home/3.jpg"></div>
        <div class="slide"><img src="../../img/images/home/4.jpg"></div>
    </div>
    <div class="border"></div>
    <div class="home-widget">
        <h3>Lorem Ipsum</h3>
        <img src="../../img/images/home/3.jpg" width="300" alt="" />
        <p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
    </div>
    <div class="home-widget">
        <h3>Lorem Ipsum</h3>
        <img src="../../img/images/home/4.jpg" width="300" alt="" />
        <p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
    </div>
    <div class="home-widget">
        <h3>Lorem Ipsum</h3>
        <img src="../../img/images/home/1.jpg" width="300" alt="" />
        <p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
    </div>
    <div class="border2"></div>
    <br />
    <aside id="pricing-table" class="clear">
        <div class="plan">
            <h3>Pizzas<span>R$99</span></h3>
            <a class="button" href="">Comprar Agora</a>
            <ul>
                <li><strong style="text-transform:uppercase">Pizza Dura</strong> R$ 251,00</li>
                <li><strong style="text-transform:uppercase">Pizza de Farinha</strong> R$ 7.255,00</li>
                <li><strong style="text-transform:uppercase">Pizza de drogas</strong> R$ 225,00</li>
                <li><strong style="text-transform:uppercase">Pizza de vento</strong> R$ 235,00</li>
            </ul>
        </div>
        <div class="plan">
            <h3>Sanduiches<span>R$99</span></h3>
            <a class="button" href="">Comprar Agora</a>
            <ul>
                <li><strong style="text-transform:uppercase">X - Salada</strong> R$ 25,00</li>
                <li><strong style="text-transform:uppercase">X - Bacon</strong> R$ 25,00</li>
                <li><strong style="text-transform:uppercase">X - Tudo</strong> R$ 25,00</li>
                <li><strong style="text-transform:uppercase">Mixto Quente</strong> R$ 25,00</li>
            </ul>
        </div>
        <div class="plan">
            <h3>Refrigerantes<span>R$99</span></h3>
            <a class="button" href="">Comprar Agora</a>
            <ul>
                <li><strong style="text-transform:uppercase">Coca Cola</strong> R$ 15,00</li>
                <li><strong style="text-transform:uppercase">Fanta Uva</strong> R$ 5,00</li>
                <li><strong style="text-transform:uppercase">Fanta Laranja</strong> R$ 5,00</li>
            </ul>
        </div>
    </aside>
</div>


