<div class="wrapper">
    <div class="border"></div>
    <article class="menu">
      <div class="left">
        <h3>Pizza Type A: $45</h3>
      </div>
      <div class="left star"><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_half_full.png" class="noeffects" alt=""><img src="../img/images/star_empty.png" class="noeffects" alt=""></div>
      <div class="right menu-order"><a class="button" href="">Order Now</a></div>
      <img src="../img/images/menu/pizza2.jpeg" class="left clear item" width="150" alt="">
      <p class="left">Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
      <div class="border3"></div>
      <div class="left">
        <h3>Pizza Type B: $40</h3>
      </div>
      <div class="left star"><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_empty.png" class="noeffects" alt=""></div>
      <div class="right menu-order"><a class="button" href="">Order Now</a></div>
      <img src="../img/images/menu/pizza4.jpeg" class="left clear item" width="150" alt="">
      <p class="left">Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
      <div class="border3"></div>
      <div class="left">
        <h3>Pizza Type C: $35</h3>
      </div>
      <div class="left star"><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_full.png" class="noeffects" alt=""></div>
      <div class="right menu-order"><a class="button" href="">Order Now</a></div>
      <img src="../img/images/menu/pizza.jpeg" class="left clear item" width="150" alt="">
      <p class="left">Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
      <div class="border3"></div>
      <div class="left">
        <h3>Pizza Type D: $30</h3>
      </div>
      <div class="left star"><img src="../img/images/star_full.png" class="noeffects" alt=""><img src="../img/images/star_half_full.png" class="noeffects" alt=""><img src="../img/images/star_empty.png" class="noeffects" alt=""><img src="../img/images/star_empty.png" class="noeffects" alt=""><img src="../img/images/star_empty.png" class="noeffects" alt=""></div>
      <div class="right menu-order"><a class="button" href="">Order Now</a></div>
      <img src="../img/images/menu/pizza3.jpeg" class="left clear item" width="150" alt="">
      <p class="left">Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae.</p>
    </article>
    <aside class="sidebar">
      <h3>why? wtf?</h3>
      <ul class="blog">
        <li><a href="#">Lorem Ipsum Dolor</a><br/>
          Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
        <li><a href="#">Praesent Et Eros</a><br/>
          Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
        <li><a href="#">Suspendisse In Neque</a><br/>
          Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
        <li><a href="#">Suspendisse In Neque</a><br/>
          Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
      </ul>
      <div class="border3"></div>
      <h3>coloco o que?</h3>
      <img src="../img/images/home/1.jpg" width="280" alt="" />
      <p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. In turpis pulvinar facilisis. Ut felis.<br>
        <a href="" class="right" style="padding-top:7px"><strong>Continue Reading &raquo;</strong></a></p>
    </aside>
  </div>