<div class="wrapper">
    <div class="border"></div>
    <article class="menu" style="width: 940px">
        <?php foreach ($this->data as $entity): ?>
            <div class="left">
                <h3><?= $entity->getDescricao(); ?>: R$ <?= number_format($entity->getPreco(), 2, ",", "."); ?></h3>
            </div>
            <div class="left star">
                <?php for ($x = 1; $x <= 5; $x++): ?>
                    <img src="../../img/images/star_full.png" class="noeffects" alt="">
                <?php endfor; ?>  
            </div>
            <div class="right menu-order"><a class="button" href="/loja"><i class="fa fa-shopping-cart"></i></a></div>
            <img src="<?= $entity->getImagem(); ?>" class="left clear item" width="150" height="150" alt="">
            <p class="left"><?= $entity->getComentario(); ?></p>
            <div class="border3"></div>
        <?php endforeach; ?>  
    </article>
</div>