<div class="row-fluid">
    <div class="navbar-inner">
        <ul class="breadcrumb">
            <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
            <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
            <a href="<?= $this->url('produto', array('controller' => 'adminproduto', 'action' => 'index')); ?>" class="active">Produtos</a>
        </ul>
    </div>
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">Produtos</div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Produto</th>
                            <th>Grupo</th>
                            <th>Valor</th>
                            <th>Editar</th>
                            <th>Deletar</th>
                        </tr>
                    </thead>
                    <?php foreach ($this->data as $entity): ?>
                        <tbody>
                            <tr>
                                <td><?= $entity->getId(); ?></td>
                                <td><?= $entity->getDescricao(); ?></td>
                                <td><?php echo $entity->getGrupo()->getDescricao(); ?></td>
                                <td><?= $entity->getPreco(); ?></td>           
                                <td><a href="#" class="btn btn-warning">E</a></td>
                                <!--<td><a href="#" class="btn btn-danger">D</a></a></td>-->
                                <td>
                                    <a href="
                                    <?= $this->url("produto", array('controller' => 'adminproduto', 'action' => 'delete', 'id' => $entity->getId())); ?>
                                       ">Deletar</a>
                                </td>
                            </tr>
                        </tbody>
                    <?php endforeach; ?>        
                </table>
            </div>
        </div>
    </div>
</div>