<div class="row-fluid">
    <div class="navbar-inner">
        <ul class="breadcrumb">
            <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
            <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
            <a href="<?= $this->url('usuario', array('controller' => 'adminusuario', 'action' => 'index')); ?>" class="active">Usuarios</a>
        </ul>
    </div>
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">Usuarios</div>
        </div>
        <div class="container-fluid">
            <br>
            <a href="<?= $this->url('usuario', array('action' => 'new')); ?>" class="btn btn-success"><i class="fa fa-check"></i> Novo</a>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Editar</th>
                            <th>Deletar</th>
                        </tr>
                    </thead>
                    <?php foreach ($this->data as $entity): ?>
                        <tbody>
                            <tr>
                                <td><?= $entity->getId(); ?></td>
                                <td><?= $entity->getNome(); ?></td>
                                <td><?= $entity->getEmail(); ?></td>
                                <td><a href="
                                    <?= $this->url("usuario", array('controller' => 'adminusuario', 'action' => 'edit', 'id' => $entity->getId())); ?>
                                       " class="btn btn-warning">
                                        <i class="fa fa-pencil-square-o"></i></a></td>
                                <td>
                                    <a href="
                                    <?= $this->url("usuario", array('controller' => 'adminusuario', 'action' => 'delete', 'id' => $entity->getId())); ?>
                                       " class="btn btn-danger">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    <?php endforeach; ?>        
                </table>
            </div>
        </div>
    </div>
</div>