<div class="row-fluid">
    <div class="navbar-inner">
        <ul class="breadcrumb">
            <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
            <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
            <a href="<?= $this->url('usuario', array('controller' => 'adminusuario', 'action' => 'index')); ?>" class="active">Usuarios</a>
        </ul>
    </div>
    <h3>Novo Produto</h3>

    <br />
    <div class="span3">
        <?php
        $form = $this->form;

        $form->setAttribute('action', $this->url('usuario', array('controller' => 'adminusuario', 'action' => 'new')));

        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>
    </div>

</div>
